### PR TITLE
Update ko.json

### PR DESCRIPTION
**Pull request by YoungCholKim**
Meaning is awkward. So I replaced the adjective with a verb.
I'm going to send another pull request for  PI demo app for Korean too.

### CODE REVIEW

**Review by yunho0130 — COMMENTED** [review]
Every translation is looks good to me, However we have to check the intention to use of "LowTerm" and "HighTerm". Is it used as a verb or adjective in the sentence?

**Review by yunho0130 — APPROVED** [review]
I reviewed the translation with test.js file which Youngchol uploaded. In the Korean context of the test.js file, the changed translation is better than the origin.

**Review by yunho0130 — APPROVED** [review]
LGTM

**Review by germanattanasio — APPROVED** [review]

**Comment by germanattanasio** [comment]
@YoungCholKim can you update the test?

**Comment by germanattanasio** [comment]
@YoungCholKim can you update the test?

**Pull request closed without merging**
